# Basic exercises: numbers, strings and string functions.
# Each function takes the decoded JSON body and returns something JSON-friendly
# (dict, list, str, number) that app.py sends back to the page.
import sys

# Adds x + y + a and says whether x > y. Body: {"x": .., "y": .., "a": ..}
def add_numbers(body):

    if body is None:
        return {"error":"missing input body"}

    
    # float() raises ValueError for text and TypeError for None (missing key).
    try:
        x = float(body.get("x"))
        y = float(body.get("y"))
        a = float(body.get("a"))
    except (TypeError, ValueError):
        return {"error": "x, y, and a must all be numbers"}

    z = x + y + a

    if x > y:
        answer = "true"
    else:
        answer = "false"

    # A tuple becomes a JSON array: [6.0, "false"]
    return(z, answer)

# This only runs if you execute this file directly from the terminal
if __name__ == "__main__":
    # Check if the user passed exactly 3 arguments (plus the script name)
    if len(sys.argv) == 4:
        # Map terminal arguments into the format your function expects
        local_body = {"x": sys.argv[1], "y": sys.argv[2], "a": sys.argv[3]}

        result = add_numbers(local_body)
        print(f"Terminal Result: {result}")

    else:
        print("Usage: python script.py <x> <y> <a>")
        print("Example: python script.py 5 10 3")


# Joins three words into one sentence. Body: {"a": .., "b": .., "c": ..}
def add_strings(body):
    # If body is None (or empty), use an empty dict so .get() still works.
    body = body or {}

    a = body.get("a")
    b = body.get("b")
    c = body.get("c")
    values = [a, b, c]

    # all(...) is True only if every value passes the test.
    if not all(isinstance(v, str) for v in values):
        return {"error": "a, b, and c must all be strings"}

    if not all(0 < len(v) <= 100 for v in values):
        return {"error": "each word must be between 1 and 100 characters"}

    return {"result": " ".join(values)}

# Returns a fixed sentence (a plain string becomes a JSON string).
def add_phrase(body=None):
    return "This is a phrase that has been autogenerated to show string functions"

# Shows two string operations on the phrase the page sends as the body.
def string_func(body):

    phrase = body

    # [:16] = the first 16 characters; .upper() = capital letters.
    slice = (phrase[:16])
    upper = (phrase.upper())

    
    return  {"slice":slice, "upper": upper}

if __name__ == "__main__":
    string_func({"text":"This is a phrase that has been autogenerated to show string functions"})
