import sys

def add_numbers(body):

    if body is None:
        return {"error":"missing input body"}

    
    try:
        x = float(body.get("x"))
        y = float(body.get("y"))
        a = float(body.get("a"))
    except (TypeError, ValueError):
        return {"error": "x, y, and a must all be numbers"}

    z = x + y + a

    if x > y:
        answer = "true"
    else:
        answer = "false"

    return(z, answer)

# This only runs if you execute this file directly from the terminal
if __name__ == "__main__":
    # Check if the user passed exactly 3 arguments (plus the script name)
    if len(sys.argv) == 4:
        # Map terminal arguments into the format your function expects
        local_body = {"x": sys.argv[1], "y": sys.argv[2], "a": sys.argv[3]}

        result = add_numbers(local_body)
        print(f"Terminal Result: {result}")

    else:
        print("Usage: python script.py <x> <y> <a>")
        print("Example: python script.py 5 10 3")


def add_strings(body):
    body = body or {}

    a = body.get("a")
    b = body.get("b")
    c = body.get("c")
    values = [a, b, c]

    if not all(isinstance(v, str) for v in values):
        return {"error": "a, b, and c must all be strings"}

    if not all(0 < len(v) <= 100 for v in values):
        return {"error": "each word must be between 1 and 100 characters"}

    return {"result": " ".join(values)}

def add_phrase(body=None):
    return "This is a phrase that has been autogenerated to show string functions"

def string_func(body):

    phrase = body

    slice = (phrase[:16])
    upper = (phrase.upper())

    
    return  {"slice":slice, "upper": upper}

if __name__ == "__main__":
    string_func({"text":"This is a phrase that has been autogenerated to show string functions"})
